### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Hellowlol** [tmjo/charger-card#1]
Thanks for this card. It looks great.I would really like that the color on the card changes with the current theme automatically like it does for many other cards.

**Comment by tmjo** [comment]
Good idea, I thought it did already. Perhaps I messed up something, I'll check.

**Comment by Hellowlol** [comment]
My card is blue regardless of what theme I use.

**Comment by tmjo** [comment]
Hmm, that's strange. Did a quick test changing my theme color to yellow, and it seems to work on my side.

![image](https://user-images.githubusercontent.com/54450177/97849396-cce2a180-1cf2-11eb-8403-d5cbb3d9a68c.png)

But I only changed the "primary color", not really a theme. Are you trying with a theme?

**Comment by Hellowlol** [comment]
Im using themes yes

**Comment by tmjo** [comment]
Hmm, ok. I'll look into it.

**Comment by tmjo** [comment]
@Hellowlol; really sorry for the delay here, but it seems my understanding of themes was not too good since I don't use it myself. Hopefully your request is covered in v0.0.9, so if you're still using the card - please let me know if it works for you. See also #5 for details.
