### ISSUE TITLE
Actions toolbar not shown after update 

### ISSUE THREAD

**Issue by sveba** [tmjo/charger-card#14]
After upgrade to 2021.11.1 the action bar is dark and the buttons for "stop, pause ..." are not visible:

<img width="471" alt="Bildschirmfoto 2021-11-07 um 09 47 48" src="https://user-images.githubusercontent.com/1735151/140638705-4dfc26d0-b99b-4dde-98bb-48839fec5852.png">

Maybe this can help https://github.com/denysdovhan/vacuum-card/issues/276

**Comment by tmjo** [comment]
Thanks for reporting and for the hint, I didn't update just yet so I didn't see this. I'll take a look!

**Comment by N3rdix** [comment]
i have exactly the same issue, buttons are there but nearly invisible. Same behavior on mobile app and for different themes...
![image](https://user-images.githubusercontent.com/70015952/140656539-b31f97b5-ca5f-4b47-b975-e2ee6a068bbc.png)

**Comment by yumagulov-azat** [comment]
+1
