### ISSUE TITLE
"click for limits"-options not showing

### ISSUE THREAD

**Issue by elgeniskogen** [tmjo/charger-card#16]
Thanks for e great card.

I use the standard card without any options set in the latest version. 

When I click "Click for limits" the card expands, but no icons are showing where the card expands to be able to make the changes.

**Comment by tmjo** [comment]
Hm, that's strange. On my side it is showing all icons after the fix, see snip below with all icons expanded:
![image](https://user-images.githubusercontent.com/54450177/141269829-3eb7d28b-32e2-46ad-897d-3a40c3337ad9.png)

You are on latest version of HA? Could be a cache issue, so perhaps a hard refresh (ctrl+f5) would help?

If it doesn't help, could you include a snip of it?

**Comment by tmjo** [comment]
Hi @elgeniskogen, did you figure this out? Perhaps I misunderstood you original post. What did you mean with "without any options set"? Do you see the limit sensors when going to Developer Tools? I just thought that it could be they are not appearing if they are disabled, that would make sense.

Cheers.

**Comment by elgeniskogen** [comment]
Thank you for following up so quickly. Sorry for not responding back. I found the problem. It seems like in the latest version of the Easee-intregation a lot of the sensors are disabled by default. When enabling these, your nice front ned works :-)
