### ISSUE TITLE
Breaking changes in easee_hass version 0.9.29

### ISSUE THREAD

**Issue by Martin-BW** [tmjo/charger-card#2]
Due to the naming of variables and services this card can't dsiplay all the values.

Would you please update the card ?

Best regards

Martin

**Comment by tmjo** [comment]
Hi,

Yes, I am aware. Update is coming in not too long I hope. Thanks for reporting, good to see that the card is in use by more people than me :)

**Comment by Martin-BW** [comment]
Cool 👍 

Thank you very much :)

**Comment by tmjo** [comment]
See latest version released just now, and let me know if it seems to be working.

**Comment by Martin-BW** [comment]
Just tested, but can't see the limits and the cable lock status.

**Comment by tmjo** [comment]
Hm, that's the ones that have been changed and were the ones I tested for. Sure you have updated cache etc? Sometimes lovelace can be a bit picky, normally CTRL+F5 in Google Chrome works (hard refresh).

**Comment by Martin-BW** [comment]
Hi, yes the card was still in the cache. I deinstalled it. After installing again, I don't get the charger card in as a custom card in the list.

Using version 0.0.3 that works. It seems that version 0.0.4 doesn't load.

**Comment by tmjo** [comment]
That's strange, I'll check more.

**Comment by Martin-BW** [comment]
There is no charger-card.js in the v0.0.4 release.

**Comment by tmjo** [comment]
You're right, look at that! Sorry, I've added it now.

**Comment by Martin-BW** [comment]
It works now.

Thank you very much.
