### ISSUE TITLE
Current limits not showing in list

### ISSUE THREAD

**Issue by runevad** [tmjo/charger-card#21]
Tried the new card and it works great! The only issue I have at the moment are that the current limits I have configured are not showing up correctly. When I click one of the settings for sending a current setting to the charger, the list is all white? The selections are there but the text is all white and the end of the list seems to disappears behind the details on the bottom of the charger card? 

![image](https://user-images.githubusercontent.com/31310911/158033115-e410996b-5a41-4170-8a56-bb2b9994e59c.png)

**Comment by tmjo** [comment]
Thanks for reporting. I just noticed myself as well, but on my testing environment I have theme applied and it didn't appear like that. I'll try to find a fix for it soon!

**Comment by tmjo** [comment]
I believe this issue was resolved quite a while ago, but I forgot to close the issue. Please re-open if there is still an issue.
