### ISSUE TITLE
Error on card - only when car is not connected

### ISSUE THREAD

**Issue by AMajland** [tmjo/charger-card#24]
I have an easee home configured with the card filled with full template from the main instruction page.

When a car is connected by cable I have the stop, resume and override schedule icons at the bottom of the card.

But when the car is not connected i get an error instead of these 3 icons.

2022-05-24 11:07:36 ERROR (MainThread) [frontend.js.latest.202205041] http://homeassistant:8123/hacsfiles/charger-card/charger-card.js?hacstag=308752409011:7113:24 Uncaught TypeError: Cannot read properties of null (reading 'entity_id') and it shows a single (?) icon.

I'm completely new to home assistant - still finding my way around like an  elephant in a porcelain store :-)

**Comment by AMajland** [comment]
I've just verified that my my config is identical to the full advanced configuration as shown on https://github.com/tmjo/charger-card (Did a diff of  my config vs the online one)

I've also verified that all the entity_id are available and active.

The only thing that comes to my mind is that the CHARGERID and CHARGERNAME is the same for me. But have not tried to look below the surface .... (yet)

**Comment by tmjo** [comment]
Hmmm, thats's kindof good. I see that if I simulate 'disconnected' as status I also get a icon '?' showing null. Do you get the error only when clicking the button, or all the time?

Seems like deleting the section

```
    default:
      - {}
    disconnected:
      - {}
```

solves it, then you get an empty toolbar. Or you could add something that makes sense while disconnected (although I couldn't really find anything).

**Comment by tmjo** [comment]
@AMajland; sorry for the delay, but if you don't mind, please check latest version just released to see if this bug is solved.

**Comment by AMajland** [comment]
Thankyou for the update.
The stop button is now shown when the car is disconnected. Pressing the stop button gives the error shown here.
![image](https://user-images.githubusercontent.com/97510471/200612937-02b99f5e-a52d-4d73-8f92-b20ab21232ec.png) - But since it is disconnected there is nothing to stop :-)

But got this error in the settings after pressing the stop button:
![image](https://user-images.githubusercontent.com/97510471/200613371-d9397854-5097-44ff-af26-29110a1d77ff.png)

**Comment by tmjo** [comment]
Well, yes, two things: Stop doesn't work when car is disconnected, and the second error message is a deprecation of some services that has been changed in the Easee integration (will be added to card soon). But the original problem was that 

```
    default:
      - {}
    disconnected:
      - {}
    
```
gave errors, right? And the workaround was to add a button (hence the stop-button).

**Comment by tmjo** [comment]
Closing this as I believe it has been solved. Please re-open if this is not the case.
