### ISSUE TITLE
list of supported models

### ISSUE THREAD

**Issue by instinxx** [tmjo/charger-card#27]
Where can I find the list of supported models?

**Comment by tmjo** [comment]
Hi,

There's no official list (work-in-progress), but the card is now fully customizable so you can make it fit any charger of your liking. I even use it to show some weatherdata and for my car. The idea is that (if people contribute) to make what I have baptized as templates to make it easy for people to configure different chargers just to avoid the hassle of doing the customization.

**Comment by tmjo** [comment]
Closing due to no update - card is now fully customizable and should be possible to adapt to different chargers with some yaml-tweaking.
