### ISSUE TITLE
Easee - Use of deprecated service: resume

### ISSUE THREAD

**Issue by yusijs** [tmjo/charger-card#31]
The easee integration is being changed from services to action commands; I got this error message when I tried clicking the Start button in your card. 

![image](https://user-images.githubusercontent.com/11261560/198139438-02e007a8-2b8a-4be3-9502-34e616c1dd85.png)

**Comment by tmjo** [comment]
Hi! Yes, I am aware. I'll fix that before the deprecation, should be fairly easy to do. Cheers.

**Comment by corvy** [comment]
![image](https://user-images.githubusercontent.com/138292/201292867-e8eb1182-9329-46d9-9731-d5a8078c9569.png)

Just for completeness I got a few more of these. I guess you are aware :)

**Comment by tmjo** [comment]
Hi. Yes, we tried to change most of the service calls to one so it is basically all that was possible to have with a 'command'.

**Comment by kirilldem** [comment]
Any more updates on this?

I get this error message:

`This stops working in version 2023.1.0. Please address before upgrading.
The use of the service stop is deprecated and the service will be removed in the future.

Please convert your automations and scripts to use action_command as soon as possible

`

**Comment by tmjo** [comment]
Hi, it should be fixed in test releases the recent days, you can test with v0.2.2-alpha (if using HACS, enable the feature to see beta-versions by clicking redownload if it is not already enabled). 

To my knowledge, the services are not yet deprecated, so there shouldn't be any problems. But if you want to test the new versions of the card, that would be nice.

**Comment by Enrica-r** [comment]
Hi, now it happened. The deprecated services have been removed with latest easee plugin release. Therefore your pause, resume, start and stop buttons don't work anymore. I hope that your test were positive and you can release this fix. Thank you very much.

**Comment by tmjo** [comment]
Hi, this is already released some time ago. But you need to update your yaml-code either by using the UI or just by doing it manually. There is no other way. Suggest to setup a new test card using the UI, and if everything looks the way you want just replace your card with the new one.

**Comment by tmjo** [comment]
Nothing heard in while, so closing issue. Please re-open if there is still an issue. 

PS! Advanced example in readme updated to reflect the changes mentioned above in Easee integration. Also, the yaml-config is not updated automatically so users need to update their configuration themselves (but UI config now helps doing this very easily, especially if no customizations were made).
