### ISSUE TITLE
Card not showing charger status since last update

### ISSUE THREAD

**Issue by Mithrox** [tmjo/charger-card#34]
Hi,

I saw the Breaking Change information, but I have changed the minimum config to the following (as per your guidance).

type: custom:charger-card
brand: easee
entity: sensor.husvegg_status
image: default

If you look at the screenshot below, there seem to be a lot of information missing which it is not pulling from the charger. However, I fully understand if I did not completely get what is needed to have it work like it did, do I need the full Advanced Config example to get the "missing_group" information to come up?

![Screenshot_20221108_060510](https://user-images.githubusercontent.com/58890682/200629387-606342d8-ea25-4b55-8df6-62017bce34ea.png)

**Comment by Mithrox** [comment]
Never mind, I found that the advanced config is now necessary, so I will dig more into it. Sorry for the trouble.

**Comment by tmjo** [comment]
Great! The idea is - when I am able to fix the UI config - that this will be very easy to setup even for people that doesn't know the advanced YAML-code. Just like it was in previous releases, but now more generic. Should become really easy, but as you discovered, for now the best solution is to go for full yaml-code manually.
