### ISSUE TITLE
Tried to add translation

### ISSUE THREAD

**Issue by nickevackerdag** [tmjo/charger-card#35]
@tmjo I tried to add a new Swedish translation to Charger Card. I can, however, not see any of the files or changes I committed. It probably is something I did/did not do. The language file is named sv-alt.json. 

Does it show on your end?

Best regards, Niklas

**Comment by tmjo** [comment]
Hi, I don't see anything. Did you make a pull request?

**Comment by tmjo** [comment]
Closing as nothing heard.
