### ISSUE TITLE
Default Easee configuration just shows status

### ISSUE THREAD

**Issue by web-dc** [tmjo/charger-card#39]
I have two Easee boxes with just a default configuration, e.g.  sensor.*_status sensors etc. But the card is nearly empty

![image](https://user-images.githubusercontent.com/49026778/216262498-43da5e22-fe23-4b27-80fe-666115d9856f.png)

As soon as I use the full easee example (https://github.com/tmjo/charger-card#advanced-example-easee-charger) and find&replace CHARGERNAME by e.g. "vorne" and CHARGERID by it's id, it works..

I'm already enabled debugging but didn't get any meaningful apart from brand name is not detected within translation?

```
CHARGER-CARD 0.1.2 IS INSTALLED 
charger-card.js:3425 Translating 1 -> de: status.disconnected --> easee.status.disconnected --> Getrennt
charger-card.js:3425 Translating 1 -> de: click_for_group1 --> click_for_group1 --> undefined
charger-card.js:3428 Translating 2 -> de lowercase: click_for_group1 --> click_for_group1 --> undefined
charger-card.js:3432 Translating 3 -> en  : click_for_group1 --> click_for_group1 --> undefined
charger-card.js:3436 Translating 4 -> en lowercase: click_for_group1 --> click_for_group1 --> undefined
charger-card.js:3445 Gave up translating: click_for_group1 --> click_for_group1 --> click_for_group1
```

Current YAML configuration:
```
- type: 'custom:charger-card'
  entity: sensor.vorne_status
  brand: easee
  debug: true
```

**Comment by tmjo** [comment]
Hi, that's strange, but I am aware there are bugs in the UI configuration which I am working to fix. Have it nearly finished, so let's wait and see. What should happen when you select Easee from the dropdown menu is that the YAML config should update itself automatically, so if it worked you should see it in the YAML-code.

Could you try to select a different brand, and then select easee again just to see if it works better?

**Comment by europeke** [comment]
I tried. Does not work. Also selecting something in the ui does not affect to change the yaml code.

**Comment by web-dc** [comment]
@tmjo Changing back and forth doesn't change anything.

**Comment by tmjo** [comment]
Noted. I'll try to speed up the next version which will fix entirely (hopefully) the UI which has been broken for quite a while. Meanwhile, try using the manual configuration, let me know if you need any help to set it up.

**Comment by tmjo** [comment]
Please test alpha-version released now. It should fix UI, but please test carefully.

**Comment by web-dc** [comment]
Unfortunately nothing really changed:

![image](https://user-images.githubusercontent.com/49026778/220032661-75a6f474-9c7e-4ecf-a06e-6f9c679f9d73.png)

  CHARGER-CARD   Version 0.2.0    
charger-card.js:832 Toolbar_left is turned on but not given in config.
charger-card.js:832 Toolbar_right is turned on but not given in config.
charger-card.js:832 Toolbar_left is turned on but not given in config.
charger-card.js:832 Toolbar_right is turned on but not given in config.


Config is again as written in my first post

**Comment by tmjo** [comment]
But is the UI editor working now? I think it may be a good idea to setup a new additional card for experimenting and testing from scratch. Select Easee in the UI-editor and the YAML should update. Please let me know how it goes.

**Comment by Barzille** [comment]
Hm, I just tried and uploaded the new charger-card.js via File Editor to /config/www/community/charger-card/charger-card.js
Is that correct? Because I don't see any changes in the behavior.

**Comment by tmjo** [comment]
> Hm, I just tried and uploaded the new charger-card.js via File Editor to /config/www/community/charger-card/charger-card.js Is that correct? Because I don't see any changes in the behavior. I have to add, I initially installed via HACS

I would recommend using HACS. There is a feature in HACS to enable showing beta versions. Go to the integration in HACS, click Re-download and there is a switch to toggle on beta versions. Then you'll see the new versions there and install it as usual.

**Comment by Barzille** [comment]
Thank you, that did the trick. UI is behaving much better now. But some icons or infos are missing:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/1096322/220387973-cb3b20e8-ddd9-4095-b33a-e0e3046ba369.png">

**Comment by tmjo** [comment]
> Thank you, that did the trick. UI is behaving much better now. But some icons or infos are missing, it's an Easee Home 

It looks like it is the entities that are missing since some of the show null in value as well. I'm not sure, but my best guess is that these entities are disabled by the Easee integration? I know it comes with some disabled as default. Go to the integration and see if it tells you some disabled ones.

Otherwise it could be that the naming of these are different from the standard, it happens sometimes if it is setup several times and some sensors get names like "_2" or it could even have been renamed. Go to developer tool -> states and see if you find "xxx_dynamic_charger_limit", "xxx_dynamic_circuit_limit" which are the two dropdowns missing. Another missing is "xxx_cost_per_kwh". My guessing it is the same problem for all. xxx is your charger name.

Of course, if you prefer not to have them on the card, you can easily customize it by editing the YAML code and simply remove the blocks corresponding to missing entities.

**Comment by Barzille** [comment]
Yes, there were disabled entities, look complete now :) Thank you,
if you could now only describe what idle current and smart charging are standing for, I am absolutely happy :)

**Comment by tmjo** [comment]
That's good to hear!

Well, [idle current](https://developer.easee.cloud/reference/post_api-chargers-id-settings) is a setting provided by Easee in charger config, and if I remember correctly it is a setting that allows the charger to draw a certain small current at any time which is typically handy for pre-heating the car if current limits are zero. Not 100% sure, but I believe it is called "Power at all times" under Site settings in the Easee app.

[Smart charging](https://developer.easee.cloud/reference/post_api-chargers-id-commands-smart-charging) is a concept provided by Easee that - to my knowledge - doesn't do much unless you have an operator providing some smart charging algoritm (like Tibber, CircleK etc). It does switch the charger leds to blue though which is supposed to be a sign of smart charging enabled. More about smart charging [here](https://developer.easee.cloud/docs/api-smart-charging) and [here](https://developer.easee.cloud/docs/settings).

**Comment by web-dc** [comment]
@tmjo I'm not using the UI editor at all. I'm doing everything via YAML configuration, maybe that's the cause of the problem?

**Comment by tmjo** [comment]
Hi. Well, if not using the UI, the YAML code must be 100% correct. Could you post the full YAML code? Did you follow the example in the readme?

There was problems with the UI editor that stopped it from doing what is what supposed to, but it should be fixed now.

What happens behind the scenes in the UI editor when selecting the main status sensor (xxxx_status) and Easee as brand, is that a script does some magic to construct the YAML code. So even if you want to do some customizations it may be benefitial to start with the UI editor, let it make the YAML and then tweak it as you like. But manual works too of course.

An example of YAML code (either manual or from UI editor):
```

type: custom:charger-card
entity: sensor.CHARGERNAME_status
customCardTheme: theme_custom
chargerImage: Red
brand: easee
show_leds: true
details:
  name:
    entity_id: sensor.CHARGERNAME_status
    attribute: name
  location:
    entity_id: sensor.CHARGERNAME_status
    attribute: site_name
  status:
    entity_id: sensor.CHARGERNAME_status
  substatus:
    entity_id: sensor.CHARGERNAME_reason_for_no_current
  smartcharging:
    entity_id: switch.CHARGERNAME_smart_charging
  currentlimits:
    - 0
    - 6
    - 10
    - 16
    - 20
    - 25
    - 32
  statetext:
    disconnected: disconnected
    awaiting_start: awaiting_start
    charging: charging
    completed: completed
    error: error
    ready_to_charge: ready_to_charge
  collapsiblebuttons:
    group1:
      text: click_for_group1
      icon: mdi:speedometer
    group2:
      text: click_for_group2
      icon: mdi:information
    group3:
      text: click_for_group3
      icon: mdi:cog
  info_left:
    - entity_id: binary_sensor.CHARGERNAME_online
      text: online
  info_right:
    - entity_id: sensor.CHARGERNAME_voltage
      text: voltage
      unit_show: true
    - entity_id: sensor.CHARGERNAME_power
      text: power
      unit_show: true
  group1:
    - entity_id: sensor.CHARGERNAME_dynamic_charger_limit
      text: dyn_charger_limit
      service: easee.set_charger_dynamic_limit
      service_data:
        charger_id: CHARGERID
        current: '#SERVICEVAL#'
    - entity_id: sensor.CHARGERNAME_dynamic_circuit_limit
      text: dyn_circuit_limit
      service: easee.set_charger_circuit_dynamic_limit
      service_data:
        charger_id: CHARGERID
        currentP1: '#SERVICEVAL#'
    - entity_id: sensor.CHARGERNAME_max_charger_limit
      text: max_charger_limit
      service: easee.set_charger_max_limit
      service_data:
        charger_id: CHARGERID
        current: '#SERVICEVAL#'
    - entity_id: sensor.CHARGERNAME_max_circuit_limit
      text: max_circuit_limit
      service: easee.set_circuit_max_limit
      service_data:
        charger_id: CHARGERID
        currentP1: '#SERVICEVAL#'
    - entity_id: sensor.CHARGERNAME_offline_circuit_limit
      text: offline_circuit_limit
      service: easee.set_charger_circuit_offline_limit
      service_data:
        charger_id: CHARGERID
        currentP1: '#SERVICEVAL#'
  group2:
    - entity_id: binary_sensor.CHARGERNAME_online
      text: online
    - entity_id: sensor.CHARGERNAME_voltage
      text: voltage
      unit_show: true
    - entity_id: sensor.CHARGERNAME_power
      text: power
      unit_show: true
    - entity_id: sensor.CHARGERNAME_current
      text: charger_current
      unit_show: true
    - entity_id: sensor.CHARGERNAME_circuit_current
      text: circuit_current
      unit_show: true
    - entity_id: sensor.CHARGERNAME_energy_per_hour
      text: energy_per_hour
      unit_show: true
    - entity_id: sensor.CHARGERNAME_session_energy
      text: session_energy
      unit_show: true
    - entity_id: sensor.CHARGERNAME_lifetime_energy
      text: lifetime_energy
      unit_show: true
  group3:
    - entity_id: switch.CHARGERNAME_is_enabled
      text: enabled
    - entity_id: switch.CHARGERNAME_enable_idle_current
      text: idle_current
    - entity_id: binary_sensor.CHARGERNAME_cable_locked
      text: cable_locked
    - entity_id: switch.CHARGERNAME_cable_locked_permanently
      text: perm_cable_locked
    - entity_id: switch.CHARGERNAME_smart_charging
      text: smart_charging
    - entity_id: sensor.CHARGERNAME_cost_per_kwh
      text: cost_per_kwh
    - entity_id: binary_sensor.CHARGERNAME_update_available
      text: update_available
    - entity_id: binary_sensor.CHARGERNAME_basic_schedule
      text: schedule
  stats:
    default:
      - entity_id: sensor.CHARGERNAME_session_energy
        text: session_energy
        unit_show: true
      - entity_id: switch.CHARGERNAME_cable_locked_permanently
        text: cable_locked
      - entity_id: binary_sensor.CHARGERNAME_basic_schedule
        text: schedule
    disconnected:
      - entity_id: sensor.CHARGERNAME_session_energy
        text: session_energy
        unit_show: true
      - entity_id: switch.CHARGERNAME_cable_locked_permanently
        text: cable_locked
      - entity_id: calculated
        text: used_limit
        unit: A
        unit_show: true
        calc_function: min
        calc_entities:
          - entity_id: sensor.CHARGERNAME_dynamic_charger_limit
          - entity_id: sensor.CHARGERNAME_dynamic_circuit_limit
          - entity_id: sensor.CHARGERNAME_max_charger_limit
          - entity_id: sensor.CHARGERNAME_max_circuit_limit
          - entity_id: sensor.CHARGERNAME_offline_circuit_limit
    awaiting_start:
      - entity_id: sensor.CHARGERNAME_session_energy
        text: session_energy
        unit_show: true
      - entity_id: binary_sensor.CHARGERNAME_basic_schedule
        text: schedule
      - entity_id: switch.CHARGERNAME_smart_charging
        text: smart_charging
      - entity_id: calculated
        text: used_limit
        unit: A
        unit_show: true
        calc_function: min
        calc_entities:
          - entity_id: sensor.CHARGERNAME_dynamic_charger_limit
          - entity_id: sensor.CHARGERNAME_dynamic_circuit_limit
          - entity_id: sensor.CHARGERNAME_max_charger_limit
          - entity_id: sensor.CHARGERNAME_max_circuit_limit
          - entity_id: sensor.CHARGERNAME_offline_circuit_limit
    charging:
      - entity_id: sensor.CHARGERNAME_session_energy
        text: session_energy
        unit_show: true
      - entity_id: sensor.CHARGERNAME_energy_per_hour
        text: energy_per_hour
        unit_show: true
      - entity_id: sensor.CHARGERNAME_circuit_current
        text: circuit_current
        unit_show: true
      - entity_id: sensor.CHARGERNAME_output_limit
        text: output_limit
        unit_show: true
      - entity_id: sensor.CHARGERNAME_current
        text: current
        unit_show: true
      - entity_id: sensor.CHARGERNAME_power
        text: power
        unit_show: true
    completed:
      - entity_id: sensor.CHARGERNAME_session_energy
        text: session_energy
        unit_show: true
      - entity_id: binary_sensor.CHARGERNAME_basic_schedule
        text: schedule
      - entity_id: calculated
        text: used_limit
        unit: A
        unit_show: true
        calc_function: min
        calc_entities:
          - entity_id: sensor.CHARGERNAME_dynamic_charger_limit
          - entity_id: sensor.CHARGERNAME_dynamic_circuit_limit
          - entity_id: sensor.CHARGERNAME_max_charger_limit
          - entity_id: sensor.CHARGERNAME_max_circuit_limit
          - entity_id: sensor.CHARGERNAME_offline_circuit_limit
    error:
      - entity_id: sensor.CHARGERNAME_session_energy
        text: session_energy
        unit_show: true
      - entity_id: binary_sensor.CHARGERNAME_basic_schedule
        text: schedule
    ready_to_charge:
      - entity_id: sensor.CHARGERNAME_session_energy
        text: session_energy
        unit_show: true
      - entity_id: binary_sensor.CHARGERNAME_basic_schedule
        text: schedule
      - entity_id: calculated
        text: used_limit
        unit: A
        unit_show: true
        calc_function: min
        calc_entities:
          - entity_id: sensor.CHARGERNAME_dynamic_charger_limit
          - entity_id: sensor.CHARGERNAME_dynamic_circuit_limit
          - entity_id: sensor.CHARGERNAME_max_charger_limit
          - entity_id: sensor.CHARGERNAME_max_circuit_limit
          - entity_id: sensor.CHARGERNAME_offline_circuit_limit
  toolbar_left:
    default:
      - {}
    disconnected:
      - {}
    awaiting_start:
      - service: easee.stop
        service_data:
          charger_id: CHARGERID
        text: stop
        icon: hass:stop
      - service: easee.resume
        service_data:
          charger_id: CHARGERID
        text: resume
        icon: hass:play
      - service: easee.override_schedule
        service_data:
          charger_id: CHARGERID
        text: override
        icon: hass:motion-play
    charging:
      - service: easee.stop
        service_data:
          charger_id: CHARGERID
        text: stop
        icon: hass:stop
      - service: easee.pause
        service_data:
          charger_id: CHARGERID
        text: pause
        icon: hass:pause
    completed:
      - service: easee.stop
        service_data:
          charger_id: CHARGERID
        text: stop
        icon: hass:stop
      - service: easee.override_schedule
        service_data:
          charger_id: CHARGERID
        text: override
        icon: hass:motion-play
    error:
      - service: easee.reboot
        service_data:
          charger_id: CHARGERID
        text: reboot
        icon: hass:restart
    ready_to_charge:
      - service: easee.stop
        service_data:
          charger_id: CHARGERID
        text: stop
        icon: hass:stop
      - service: easee.override_schedule
        service_data:
          charger_id: CHARGERID
        text: override
        icon: hass:motion-play
  toolbar_right:
    default:
      - service: persistent_notification.create
        service_data:
          message: Firmware update is available, but only possible when disconnected!
          title: Update
        text: update
        icon: mdi:file-download
        conditional_entity: binary_sensor.CHARGERNAME_update_available
    disconnected:
      - service: easee.update_firmware
        service_data:
          charger_id: CHARGERID
        text: update
        icon: mdi:file-download
        conditional_entity: binary_sensor.CHARGERNAME_update_available
```

**Comment by tmjo** [comment]
Nothing heard in a while, so assuming things are alright. Please re-open if it isn't.
