### ISSUE TITLE
Easee Home max circuit limit missing values

### ISSUE THREAD

**Issue by Barzille** [tmjo/charger-card#42]
There are some values missing in the drop-down 

![3148A7F5-FE3D-4ADC-932E-0E30FCA92998](https://user-images.githubusercontent.com/1096322/221247948-6e93f0b7-0f3f-49f7-849b-9a06d58d2deb.png)

vs

![3B731FC1-B710-46D8-B6DF-2CE00F0F5C86](https://user-images.githubusercontent.com/1096322/221248319-74fdbc3f-da10-44ac-a4ee-905d3950c91c.jpeg)

**Comment by tmjo** [comment]
Hi! That is not missing, it just the way I implemented it. It is fully customizable, so you can change the values in the dropdowns to whatever you feel appropriate for your installation. Too many values won't look nice though, especially not on mobile, but you can choose to implement the ones you prefer.
