### ISSUE TITLE
app-drawer-layout is no longer used in HA 2023.4

### ISSUE THREAD

**Issue by dreimer1986** [tmjo/charger-card#45]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
0.2.3
**Last working release (if known):**
-
**Browser and Operating System:**

**Description of problem:**

I must admit I did not see any difference, but many custom cards are in hell freezing over mode thanks to this:

app-drawer-layout was replaced by mwc-drawer. Thus the one instance of querySelector("app-drawer-layout partial-panel-resolver") in the release might need some fixing.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by tmjo** [comment]
Hi and thanks for reporting. I didn't test this version myself, but I'll update my dev container and check. If I understand correctly, it seems like that card is working although you saw this messagte?

**Comment by dreimer1986** [comment]
Yes it does. Maybe just coming from a dependency. As I did not find this line in your source I assume that you just need the new dev container and this would fix the dependencies. Even the likely not used one I talk about.

**Comment by tmjo** [comment]
I see there are some discussions on HA Discord about the issue, seems to be related to a dependency in custom-card-helpers. I'll pay attention and see what happens.

**Comment by tmjo** [comment]
Not seeing any problems here. Closing issue, but please re-open if you still see the warning.
