### ISSUE TITLE
How to change the language

### ISSUE THREAD

**Issue by HunZ83** [tmjo/charger-card#50]
I would like to display the card in german language, but I don´t know how to do so.
HA-languange is german and region is germany.
Thank you for a hint.

**Comment by tmjo** [comment]
Hi and thanks for using the card. It should be enough to have German selected as language in HA. I see that the German translation is missing quite a few texts (probably after the recent updates), so it could use an update. Hopefully you see some German texts in your setup too, just that a lot is still English because it is missing translations?

Here is how it looks in my installation when switching to German. As you see, some texts in German, but also a lot in English.

![image](https://user-images.githubusercontent.com/54450177/236454644-be2bd76b-41ea-4ae1-94ae-89f783e348de.png)

If you would like to contribute to the translations, feel free to do so by modifying [this file](https://github.com/tmjo/charger-card/blob/master/src/localize/languages/de.json) and proposing a PR. It is fairly simple, and you just need to replace the English text on the right side of the colon.

We could also kindly ask @DeerMaximum to take a look as he was the one initiating the German translation.

**Comment by tmjo** [comment]
@HunZ83; Please update to latest version for updated German translation. Thanks to @DeerMaximum!

**Comment by HunZ83** [comment]
Hello tmjo, thanks for your quick reply. I updated to the newest version this morning and also double-checked an my region-settings... I still see not a single german word on my charger card...
![image](https://user-images.githubusercontent.com/77784246/236769257-7ce70956-3f12-4bb4-a17d-f73c2cef79a2.png)
![image](https://user-images.githubusercontent.com/77784246/236769397-324291ff-b521-462f-a47d-11a4bd042c49.png)

**Comment by HunZ83** [comment]
it´s also set to "deutsch" 
![image](https://user-images.githubusercontent.com/77784246/236781035-40436c74-5c94-4b15-bce2-e8acbd6d59fd.png)

**Comment by tmjo** [comment]
Ok. Then the only thing I can think of is some kind of caching being wrong. Try to do a hard reload (CTRL+F5 in Chrome, not sure for other browsers) or even clear cache in the browser. Perhaps testing a different browser could reveal if it is really a cache problem or not.

You could also check the YAML-code for the card and verify that the localize-attribute is not set to true (or better yet, not set at all). If you post your YAML-code I can take a look too. If you've had the card for a long time, a good test could try to configure a brand new one from skratch just for testing. Perhaps there are some old data that is making the translation go bad, there has been some significant changes over the last months.

In my installation German is working fine:
![chrome_jr69LZNwSJ](https://user-images.githubusercontent.com/54450177/236829098-6e5a6017-da08-4a31-800a-d6713a3198e3.gif)

**Comment by HunZ83** [comment]
it´s really strange.... My easee-integration shows all sensors in german language:
![image](https://user-images.githubusercontent.com/77784246/236840021-f7efec50-dca2-4efb-8dd2-4fed799b30fc.png)
however, the card (even a brand new one) translates the state to english somehow... 
![image](https://user-images.githubusercontent.com/77784246/236841703-038898d9-02ca-40ac-97e7-1dcfc8d8dd84.png)

The effect is visible in all kind of browsers (chrome, fully kisk browser, HA-Android app).

Thank you for your effort, though! Imostly use the evcc-view for charging and therefore it´s not as bad for me. Still funny, that it seems to be a very rare behaviour...

**Comment by HunZ83** [comment]
always up to date...
![image](https://user-images.githubusercontent.com/77784246/237019743-ccfa15d0-4294-43db-856c-49cdbe9842f9.png)

**Comment by tmjo** [comment]
Right. I didn't update mine yet since I saw there was a lot of trouble with this release, but perhaps it is related somehow. I'll check when I update.

**Comment by HunZ83** [comment]
i have the card in use for more than a year now. afaik there has never been a german translation, therefore I doubt there is any relation with any recent release. 
Could I somehow "delete" the whole installation and start the integration from scratch?

**Comment by tmjo** [comment]
It could be worth trying to delete the card and re-install.

I did some changes yesterday which is not release yet (but will be quite soon) where i found out that English GB (en-gb) was not translating as well. I think this is what I saw in my dev container, and although the translation file was there it was never included. Additionally I added a debug line to check which language is detected and which is choosen, perhaps that could tell you something. For debug to show, you must add `debugging: true` to the card config and check developer tools in browser (CTRL+SHIFT+I in Chrome).

You should also check if the YAML-config if the `localize `attribute is NOT set to false (it will disable all translations). It is inteded if somebody wants to do their own custom "translation", which is of course a workaround you could apply if you want although it is a lot of work. In this case you can just whatever you want in the `text` attribute of each entity.

**Comment by tmjo** [comment]
Nothing heard for a while, so assuming issue is solved. Please re-open if it isn't ok.

**Comment by blackbird0589** [comment]
Hi together, I had the same "problem" and just changed the wording in the yaml configuration.
But now I've found this thread and could solve the hole problem on my system. Just tried to change the language in user-setting's from orinin to f.e. english and backward to your preferred one. And this worked automatically for all configurated cards.
