### ISSUE TITLE
update automation exempel

### ISSUE THREAD

**Issue by strand17** [tmjo/charger-card#55]
The Advanced example (Easee charger) is not working. After last easee update this automation dosent work.

**Comment by tmjo** [comment]
Sorry, you would have to be more specific.

**Comment by strand17** [comment]
Too pause or resume charger you have to call this service:

 service: easee.action_command
data:
  device_id: YOU DEVICE ID
  action_command: stop

**Comment by tmjo** [comment]
Yes, you are right. This is already correct if you choose Easee from the UI configuration, but I seem to have forgotten to update the example as you mention. Will update it.

**Comment by tmjo** [comment]
Updated readme today.
