### ISSUE TITLE
Sensor reason for no current shows with underscores

### ISSUE THREAD

**Issue by slashbv** [tmjo/charger-card#58]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
Hello,
I don't know if there is something in my settings or a bug. I am using latest version of the card and latest version of HA. See below:

![image](https://github.com/tmjo/charger-card/assets/59421121/61455081-a77d-442c-9805-07df769a24d7)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by tmjo** [comment]
Hi,

Will try to take a look. Could you share the yaml-code of the card config? And also, which language do you have set in HA?

**Comment by slashbv** [comment]
the code is as in your example
for language see below:
![image](https://github.com/tmjo/charger-card/assets/59421121/03cbaa4f-eea6-468d-8e15-3a1684afe119)

**Comment by slashbv** [comment]
I also tried with country United States, but it's the same

**Comment by slashbv** [comment]
another example:
![image](https://github.com/tmjo/charger-card/assets/59421121/5b92dcb4-d283-4a02-a653-bf0e4b985ba7)

Maybe there is some setting somewhere, I just don't know where.

**Comment by tmjo** [comment]
Strange. It seems like translations are not completed. Some suggestions to try:

- Try to setup a brand new card in a different dashboard just for testing (just delete it afterwards). See if anything changes/improves in the new setup.
- Look in your yaml code if there is anywhere saying `localize: false` which is a config setting to disable all translations. If it is there, just delete the line.
- Try to change your language to for instance Deutsch and see if there is anything translated at all. I just tested both English, English(GB) and Deutsch and it works fine in my instance.
- Add to your yaml code `debug: true` and then open the browser Developer Tools (Ctrl+Shift+I in Chrome). See if anything useful comes in the console log there that may be useful to figure out what is going on.

Remember to do a hard refresh of the webpage after each change (Ctrl+F5 in Chrome).

**Comment by slashbv** [comment]
Problem solved, thank you very much. In my profile I changed the language to Deutsch and the translation worked. Then I changed back to English and now English works too.

**Comment by tmjo** [comment]
Glad it was solved. Not 100% sure, but I believe the system/general settings are just default values while it is the user profile which actually takes effect if it is set differently.  Don't know why it didn't work in the first place though, but as long as it is working now I guess we're happy :)

**Comment by slashbv** [comment]
yes, all good now. Thanks a lot for your help.

**Comment by tmjo** [comment]
Noted, I can add it. Problem is that there has never been a complete list from Easee, so it is mostly based on what we've seen every now and then.

**Comment by slashbv** [comment]
thank you, if I see more I will add here.
