### ISSUE TITLE
Error message in HomeAssictant Log: "Validation of translation placeholders for localized (de) string"

### ISSUE THREAD

**Issue by JavanXD** [tmjo/charger-card#63]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Description of problem:**

Logger: homeassistant.helpers.translation
Quelle: helpers/translation.py:279
Erstmals aufgetreten: 12:50:57 (2 Vorkommnisse)
Zuletzt protokolliert: 12:50:57

Validation of translation placeholders for localized (de) string component.easee.device_automation.condition_type.error_pen_fault failed: (set() != {'entity_name'})
Validation of translation placeholders for localized (de) string component.easee.device_automation.trigger_type.error_pen_fault failed: (set() != {'entity_name'})

![Screen Shot 2024-05-03 at 13 15 32 PM](https://github.com/tmjo/charger-card/assets/4342160/ea8010cb-a0ed-4711-ace3-81b14612b86d)

Every time I boot the Home Assistant the Charger Card is causing those error messages. I do have the Home Assistant localication set to German (DE).

**Comment by tmjo** [comment]
Hi. Are you sure this is for the card and not for the Easee integration?

**Comment by JavanXD** [comment]
it's related to https://github.com/nordicopen/easee_hass/issues/403
