### ISSUE TITLE
Cost and currency doesn't show as in easee cloud

### ISSUE THREAD

**Issue by slashbv** [tmjo/charger-card#8]
I have set up the cost and currency in easee.cloud but it seems they are not shown in the sensor.

![image](https://user-images.githubusercontent.com/59421121/123270120-e5acfb00-d4ff-11eb-921e-51c991ab7bb1.png)
![image](https://user-images.githubusercontent.com/59421121/123270147-ecd40900-d4ff-11eb-8356-8d54a01ca4cf.png)

**Comment by slashbv** [comment]
I am closing this as it seems it was updated after many hours.

**Comment by tmjo** [comment]
I'm only guessing, but perhaps Easee put some limitations on how often it is updated. They had some serious trouble with too much traffic on their systems some time back.
